[package]
name="motor_test"
version="0.1.0"
edition="2021"
publish=false

[dependencies]
eframe="0.22.0"
motor={path="../motor"}
serial={path="../serial", features=["std", "debug"], default_features=false}

[[bin]]
name="motor_test"
path="src/main.rs"