[package]
name = "motor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial ={path="../serial"}

[features]
no_std=[]